apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistic-api
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistic-api
  template:
    metadata:
      labels:
        app: logistic-api
    spec:
      containers:
        - name: logistic-api
          image: 'rannybal2024/logistic-api:IMAGE_TAG'
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: 2000Mi
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600